using HR.Domain.Enums;

namespace HR.Application.Features.Employees.DTOs;

public record CreateEmployeeRequest(
    Guid UserId,
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Suffix,
    DateTime HireDate,
    EmploymentStatus Status,
    string? EmploymentType,
    Guid? DepartmentId,
    Guid? PositionId,
    Guid? ManagerId,
    string? EmployeeNumber,
    DateTime? DateOfBirth,
    string? Gender,
    string? CivilStatus,
    string? Nationality,
    string? PhoneNumber,
    string? Address,
    string? City,
    string? Province,
    string? ZipCode,
    string? SssNumber,
    string? PhilHealthNumber,
    string? PagIbigNumber,
    string? TinNumber
);

public record UpdateEmployeeRequest(
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Suffix,
    DateTime HireDate,
    DateTime? RegularizationDate,
    DateTime? ResignationDate,
    EmploymentStatus Status,
    string? EmploymentType,
    Guid? DepartmentId,
    Guid? PositionId,
    Guid? ManagerId,
    DateTime? DateOfBirth,
    string? Gender,
    string? CivilStatus,
    string? Nationality,
    string? PhoneNumber,
    string? Address,
    string? City,
    string? Province,
    string? ZipCode,
    string? ProfilePhotoUrl,
    string? SssNumber,
    string? PhilHealthNumber,
    string? PagIbigNumber,
    string? TinNumber
);

public record EmployeeListDto(
    Guid Id,
    string EmployeeNumber,
    string FullName,
    string FirstName,
    string LastName,
    string Email,
    string? DepartmentName,
    string? PositionTitle,
    string Status,
    DateTime HireDate,
    bool IsActive
);

public record EmployeeDetailDto(
    Guid Id,
    Guid UserId,
    string EmployeeNumber,
    string FullName,
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Suffix,
    string Email,
    DateTime? DateOfBirth,
    string? Gender,
    string? CivilStatus,
    string? Nationality,
    string? PhoneNumber,
    string? Address,
    string? City,
    string? Province,
    string? ZipCode,
    string? ProfilePhotoUrl,
    DateTime HireDate,
    DateTime? RegularizationDate,
    DateTime? ResignationDate,
    string Status,
    string? EmploymentType,
    Guid? DepartmentId,
    string? DepartmentName,
    Guid? PositionId,
    string? PositionTitle,
    Guid? ManagerId,
    string? ManagerName,
    string? SssNumber,
    string? PhilHealthNumber,
    string? PagIbigNumber,
    string? TinNumber,
    DateTime CreatedAt,
    DateTime UpdatedAt
);
